###Создать нового пользователя (вертуть accessToken ?)
POST localhost:8081/api/signUp
Content-Type: application/json

{
  "userId": 1,
  "email": "sidikov.marsel@gmail.com",
  "password": "qwerty007!"
}


###Вернуть данные пользователя
GET localhost:8081/api/auth/1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwicm9sZSI6IlVTRVIiLCJleHAiOjE2NDEzNjY2MTIsInN0YXR1cyI6IkNPTkZJUk1FRCJ9.x9okR-CK47NdzH22gqf6EiA136u19idusikCXWWkquI


###Вернуть данные пользователя
POST localhost:8081/api/auth
Content-Type: application/json

{
  "userId": 1,
  "email": "sidikov.marsel@gmail.com",
  "password": "qwerty007!"
}


