-- auto-generated definition
create table if not exists account
(
    id            bigint generated by default as identity
        constraint account_pkey
            primary key,
    date_created  timestamp not null,
    is_active     boolean   not null,
    date_modified timestamp not null
);

alter table account
    owner to postgres;

-- auto-generated definition
create table if not exists operation_type
(
    id          bigint generated by default as identity
        constraint operation_type_pkey
            primary key,
    description varchar(4096),
    type        varchar(255) not null
);

alter table operation_type
    owner to postgres;

create table if not exists operation
(
    id                bigint generated by default as identity
        constraint operation_pkey
            primary key,
    date_time         timestamp      not null,
    initiator         bigint         not null,
    sum_payment       numeric(19, 2) not null,
    credit_account_id bigint         not null
        constraint fkpp0wwfdkdklygaqnax5jo2btm
            references account,
    debit_account_id  bigint         not null
        constraint fkivu81wsl206arow2axa3011dd
            references account,
    operation_type    bigint         not null
        constraint fkn9whh6oq497xm8tawg3dq08gk
            references operation_type
);

alter table operation
    owner to postgres;


-- auto-generated definition
create table if not exists payment
(
    id           bigint generated by default as identity
        constraint payment_pkey
            primary key,
    date_time    timestamp      not null,
    sum_payment  numeric(19, 2) not null,
    account_id   bigint         not null
        constraint fkqg9hvuj0jh5jkd3ejm3ibfn10
            references account,
    operation_id bigint         not null
        constraint fk85d63fdn2u30kthiridlbhfnc
            references operation
);

alter table payment
    owner to postgres;

