PUT localhost:8082/api/account/1
Content-Type: application/json

{
  "id":1,
  "isActive":true,
  "createdAt":"2021-12-01T13:45:29Z",
  "modifiedAt":"2021-12-01T15:45:37Z"
}

###
GET localhost:8082/api/account/1
