### Получить данные о счете
GET localhost:8082/api/account/1

###Создать новый счет
POST localhost:8082/api/account
Content-Type: application/json

{
  "isActive":true,
  "createdAt":"2021-12-01T13:45:29Z",
  "modifiedAt":"2021-12-02T12:16:37Z"
}


### Изменить счет
PUT localhost:8082/api/account/3
Content-Type: application/json

{
  "isActive":true,
  "createdAt":"2022-12-01T13:45:29Z",
  "modifiedAt":"2022-12-02T12:16:37Z"
}


